apiVersion: v1
kind: ServiceAccount
metadata:
  name: kt-pod
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kt-pod-role
  namespace: default
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "watch"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["create", "get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kt-pod-rolebinding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: kt-pod
    namespace: default
roleRef:
  kind: Role
  name: kt-pod-role
  apiGroup: rbac.authorization.k8s.io
